# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy
    cache: dim/cache

    #filtre pour les avatars des utilisateurs avec son nom son type, ça taille et son mode de découpe
    filter_sets:
        avatar:
            filters:
                thumbnail:
                    size: [80,80]
                    mode: outbound
